# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 개발 노트
author: Yun SangJun
email: ysj188cm@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  iOS를 시작으로 개발자의 길로 들어서 모바일 프레임워크와 애플리케이션을 개발했고
  이후, 웹 개발자로 커리어를 전환해 웹 프레임워크, IDE를 개발했습니다.
  최근에는 Kubernetes 및 Cloud 환경에서 애플리케션을 개발하고 빌드, 배포, 모니터링하는 운영 단계를 자동화하는
  DevOps 엔지니어링을 하고 있습니다.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://yunsangjun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
disqus:
  shortname: sj-blog
google_analytics: UA-118802050-1

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

#Social networks
#twitter_username: sjyun2
github_username: yunsangjun
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#rss: rss

# Build settings
markdown: kramdown
future: true
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
#show_excerpts: true
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
